### ISSUE TITLE
Support handling failed ActiveJob tasks

### ISSUE THREAD

**Issue by Fodoj** [keypup-io/cloudtasker#22]
If ActiveJob job fails, then CloudTasker returns 422 error code and that's it. Cloud Tasks will keep re-trying this job for some time, but that's about it. We are using Rollbar to report about exceptions, but in this case exception will never reach Rollbar (or other exception tracking systems I would assume) because every error is rescued here https://github.com/keypup-io/cloudtasker/blob/a50776d3f7fd113dd1d8d01a9af5def5a28c13c8/app/controllers/cloudtasker/worker_controller.rb#L30.

**Comment by alachaum** [comment]
Thanks for reporting @Fodoj . So just to confirm, any use of `Logger.error` will not impact the exceptions reported in Rollbar?

The reason for returning `422` is to be explicit about the fact that the job failed but the framework didn't. Job failures are expected and that's why I made the choice of not returning a `503` (unhandled server exception).

I'll do a bit of bit digging to see if there is a more graceful approach for this. My initial thinking is to give users the option to configure a lambda - in the Cloudtasker config - to be invoked on error. This would allow users to manually report error to their monitoring service - for all jobs.

In the meantime you should be able to manually report the error to Rollbar using the ActiveJob `around_perform` callback (rescue => send to Rollbar => re-raise).

**Comment by Fodoj** [comment]
>  any use of Logger.error will not impact the exceptions reported in Rollbar

Exactly - Rollbar alerts on new exceptions, but if there was nothing raised, it won't know.

> The reason for returning 422 is to be explicit about the fact that the job failed but the framework didn't. Job failures are expected and that's why I made the choice of not returning a 503 (unhandled server exception).

Only problem is that the error is also not in the standard logs that rails stdouts (to cloud run, for example), so we can't see what happened, only that it retured 422 error :-)

If the job raises exception, then application would return 500, which is basically what happened in our case (exception in the application code).

**Comment by alachaum** [comment]
I'd like to still be able to differentiate framework errors (500) from job errors (422). 

My preferred approach would be to specify a lambda in the `Cloudtasker` initializer allowing users to specify error reporting strategies. Would the below work for you?

E.g. with Rollbar

```ruby
Cloudtasker.configure do |config|
  ...

  config.on_error = ->(worker, exception) { Rollbar.error(exception) }
end
```

Regarding Rails stdout, I'm a bit surprised. By default Cloudtasker configures itself to use the Rails logger when available. Then exception are reported here https://github.com/keypup-io/cloudtasker/blob/a50776d3f7fd113dd1d8d01a9af5def5a28c13c8/app/controllers/cloudtasker/worker_controller.rb#L32

Are you saying you do not see any stack trace in the logs? Do you have a specific config for your logging?

**Comment by Fodoj** [comment]
> I'd like to still be able to differentiate framework errors (500) from job errors (422).

For example, in my case we made a mistake in the code, and code raised an exception. This would happen every time job runs, not just sometimes.

What would be the example of a framework error?

> Are you saying you do not see any stack trace in the logs? Do you have a specific config for your logging?

Yes, nothing, only 422 error from CloudTasker and thats it. We log everything to stdout, on CloudRun. And stack trace wont ever be in the log, because CloudTasker current rescues any exception. No exception raised - no stack trace :)

**Comment by alachaum** [comment]
@Fodoj I'm resuming work on this issue. 

Putting rollbar aside for a moment I'd like to understand why you do not see any stack trace in your logs. That's definitely unusual considering that any error will be logged by Cloudtasker and that Cloudtasker is configured to use the Rails logger by default.

**So a few questions about your setup:**
- In your `cloudtasker.rb` initializer, did you configure a specific value for `config.logger`?
- In development, when an error is raised in a job, do you see the stack trace in the logs?
- In production, I understand you do not see the stack trace. Would you be able to share with me your logging config from your `production.rb`?

Note that ActiveJob has its own error logger - independently of Cloudtasker error handling, which includes returning 422 on job failure - so it's really weird that you do not see anything on job failure.

Using the Cloudtasker `examples/rails` project and putting an undefined variable at the top of the perform method you should see the following at least.

```
[ActiveJob] [ExampleJob] [523cacbe-7d81-44f2-8d9d-62fc80342e72] Error performing ExampleJob (Job ID: 523cacbe-7d81-44f2-8d9d-62fc80342e72) from Cloudtasker(default) in 0.96ms: NameError (undefined local variable or method `foo' for #<ExampleJob:0x00007fc67410cf38>):
/Users/arnaud.lachaume/Sites/cloudtasker/examples/rails/app/jobs/example_job.rb:7:in `perform'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/execution.rb:40:in `block in perform_now'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/i18n-1.8.5/lib/i18n.rb:313:in `with_locale'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `instance_exec'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `instance_exec'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `block in instrument'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `instrument'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/logging.rb:45:in `block in tag_logger'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `tagged'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/logging.rb:45:in `tag_logger'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `instance_exec'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:139:in `run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/execution.rb:39:in `perform_now'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/execution.rb:25:in `block in execute'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/execution_wrapper.rb:84:in `wrap'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/reloader.rb:71:in `wrap'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `instance_exec'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:139:in `run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activejob-6.0.3.3/lib/active_job/execution.rb:23:in `execute'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/active_job/queue_adapters/cloudtasker_adapter.rb:77:in `perform'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/worker.rb:357:in `block in execute_middleware_chain'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/middleware/chain.rb:216:in `block in invoke'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/batch/middleware/server.rb:9:in `block in call'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/batch/job.rb:387:in `execute'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/batch/middleware/server.rb:9:in `call'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/middleware/chain.rb:218:in `block in invoke'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/cron/middleware/server.rb:9:in `block in call'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/cron/job.rb:186:in `execute'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/cron/middleware/server.rb:9:in `call'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/middleware/chain.rb:218:in `block in invoke'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/unique_job/middleware/server.rb:9:in `block in call'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/unique_job/lock/base_lock.rb:65:in `execute'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/unique_job/middleware/server.rb:9:in `call'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/middleware/chain.rb:218:in `block in invoke'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/middleware/chain.rb:221:in `invoke'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/worker.rb:348:in `execute_middleware_chain'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/worker.rb:188:in `execute'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/worker_handler.rb:79:in `with_worker_handling'
/Users/arnaud.lachaume/Sites/cloudtasker/lib/cloudtasker/worker_handler.rb:56:in `execute_from_payload!'
/Users/arnaud.lachaume/Sites/cloudtasker/app/controllers/cloudtasker/worker_controller.rb:20:in `run'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:195:in `process_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `block in instrument'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `instrument'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.3.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:136:in `process'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionview-6.0.3.3/lib/action_view/rendering.rb:39:in `process'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:190:in `dispatch'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:254:in `dispatch'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:834:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/railties-6.0.3.3/lib/rails/engine.rb:527:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/railties-6.0.3.3/lib/rails/railtie.rb:190:in `public_send'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/railties-6.0.3.3/lib/rails/railtie.rb:190:in `method_missing'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:834:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activerecord-6.0.3.3/lib/active_record/migration.rb:567:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:101:in `run_callbacks'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:37:in `call_app'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `block in call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `tagged'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/activesupport-6.0.3.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/static.rb:126:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/railties-6.0.3.3/lib/rails/engine.rb:527:in `call'
/Users/arnaud.lachaume/.rvm/gems/ruby-2.5.5/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
/Users/arnaud.lachaume/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/Users/arnaud.lachaume/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/Users/arnaud.lachaume/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by alachaum** [comment]
@Fodoj I would be keen to get you feedback on `v0.12.rc9` if you have some spare time. I've reworked exception management a bit to pass the native exception to the logger instead of preformatting it. This may help with the issue you were having.

**Comment by Reizar** [comment]
@alachaum I'm running into the same issue here. I use BugSnag to catch any exceptions thrown and just realized earlier that none of my ActiveJob exceptions were being passed to BugSnag.

From what I understand, libraries like BugSnag and Rollbar don't really work off of logs, they deal with capturing exceptions themselves. 

My current workaround / solution for this, is this:
```ruby
# /app/jobs/application_job.rb

class ApplicationJob < ActiveJob::Base
  rescue_from(StandardError) do |exception|
    if Rails.env.staging? || Rails.env.production?
      Bugsnag.notify(exception)
    end
    
    raise exception
  end
end
```

Alongside my ActiveJob Jobs, I also have pure CloudTasker workers, ( This is basically because scheduling does not support ActiveJob, so any tasks that are required to be cron scheduled, are done by a worker and then might call an ActiveJob to process.
```ruby
# /app/workers/example_worker.rb

class ExampleWorker
  include Cloudtasker::Worker

  def perform
    # Some code here
  end

  def on_error(exception)
    if Rails.env.staging? || Rails.env.production?
      Bugsnag.notify(exception)
    end
  end
end
```

A solution like you mentioned above of:
```ruby
Cloudtasker.configure do |config|
  config.on_error = ->(worker, exception) { Rollbar.error(exception) }
end
```

Would work just fine for my needs, so long as that lambda was run for both regular CloudTasker workers and ActiveJob Job's.

PS: Thank you for all the hard work on Cloudtasker ( and your blog posts about running rails on cloud run ), they've all been incredibly helpful!

**Comment by alachaum** [comment]
@Reizar no worries, my pleasure :)

I actually wonder how BugSnag and Rollbar capture exceptions with regular ActiveJob (= without Cloudtasker). I'm surprised that it doesn't work out of the box considering ActiveJob has its own error handling.

In any case, I will add this `on_error` hook. It's the easiest way to give users central control on error reporting. It should be available soon in the next release candidate.

**Comment by alachaum** [comment]
@Reizar I've just published [v0.12.rc11](https://rubygems.org/gems/cloudtasker/versions/0.12.rc11) with support for global `on_error` and `on_dead` callbacks. Documentation [has been updated](https://github.com/keypup-io/cloudtasker#global-callbacks).

Feel free to give it a try and let me know what you think.

**Comment by Reizar** [comment]
@alachaum Awesome, thanks for that!

Initial testing in development looks like its working great. I'll do some testing in our staging environment tomorrow when I'm back in the office to see if I can find any issues.

**Comment by Reizar** [comment]
@alachaum looks to be working smoothly in our staging environment. So no issues from my end.

Thanks!!

**Comment by alachaum** [comment]
Great to hear! We're in the final stages of testing for v0.12.0. The official version should come out soon.

**Comment by alachaum** [comment]
Closing this issue as `v0.12.0` has been released.
